version: '3'
services:
  core-servive:
    build: .
    image: core-service:1.0
    network_mode: host
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_RUN_HOST=${FLASK_RUN_HOST}
      - FLASK_ENV=${FLASK_ENV}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env
    volumes:
      - data_volume:/app/data
      - ./logs:/var/log/Core-Service

volumes:
  data_volume:

networks:
  default:
    name: milvus