version: '3'
services:
  web:
    build: .
    image: core-service:1.0
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_RUN_HOST=${FLASK_RUN_HOST}
      - FLASK_ENV=${FLASK_ENV}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env
    volumes:
      - data_volume:/app/data
      - ./logs:/var/log/Core-Service

volumes:
  data_volume:
