# General configuration
model: 'OpenAI'
database: 'milvus'
splitter_name: "RecursiveCharacterTextSplitter"
logging_path : ""

# PostgreSQL configuration
pgvector:
  driver: 'psycopg2'
  host: ''
  port: ''
  database: ''
  user: ''
  password: ''

# Milvus configuration
milvus:
  host: ''
  port: ''
  user: 'test'
  password: 'test'

# OpenAI configuration
openai:
  model_name: 'gpt-3.5-turbo'
  temperature: 0.7
  max_tokens: 1024
  buffer_top_k: 10

# Splitter configuration
splitter:
  separator:
    - "\n\n"
    - "\n"
    - " "
  chunk_size: 1000,
  chunk_overlap: 200,

